Remove conflicting disable section from golangci-lint config
Error: can't combine options --disable-all and --disable typecheck

Fix: Remove the disable: section entirely since we're using
disable-all: true with an explicit enable: list. typecheck is
already excluded by not being in the enable list.